name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: extract 
        run: make extract 
      - name: transform
        run: make transform
      - name: query
        run: make query
      - name: test
        env : 
          databricks_api_key : ${{ secrets.DATABRICKS_API_KEY }}
          echo "sql_server_host : ${{ secrets.SQL_SERVER_HOST }}
          echo "sql_http : ${{ secrets.SQL_HTTP }}
        run: make test
      - name: format
        run: make format
